# authentication error messages
authentication.err.validation.authenticator.notfound=Mislykkedes at autentificere, autentificerer med navn, {0}, ikke fundet
authentication.err.validation.authenticator.notactive=Autentificerer er ikke aktiv

authentication.err.authentication=Mislykkedes at autentificere, brugernavn eller adgangskode er forkert. Brugernavn:{0} \u00c5rsag {1}
authentication.err.connection=Mislykkedes at forbinde til {0}. \u00c5rsag {1}
authentication.err.communication=Mislykkedes at kommunicere til {0}. \u00c5rsag {1}

# LDAP error messages
authentication.err.connection.ldap.authenticator.unknownhost=Mislykkedes at forbinde, LDAP v\u00e6rt {0} er ikke kendt
authentication.err.connection.ldap.user.notfound=LDAP bruger {0} ikke fundet
authentication.err.connection.ldap.manager.notfound=LDAP Manager bruger {0} ikke fundet
authentication.err.connection.ldap.search=Kunne ikke s\u00f8ge i LDAP. \u00c5rsag {0}

# PASSTHRU
authentication.err.connection.passthru.server=Mislykkedes at \u00e5bne session til passthru server
authentication.err.passthru.token.unsupported=Ikke underst\u00f8ttet autentificerings token type
authentication.err.passthru.guest.notenabled=G\u00e6ste logind deaktiveret
authentication.err.passthru.user.disabled=Konto deaktiveret
authentication.err.passthru.user.notfound=Passthru bruger {0} ikke fundet

# Authentication Diagnostic Steps
authentication.step.ldap.validation=Validering af foresp\u00f8rgsel
authentication.step.ldap.connecting=Forbinder til LDAP server {0} 
authentication.step.ldap.connected=Forbundet til LDAP server {0} med hoved: {1}
authentication.step.ldap.lookup=Finder test bruger brugernavn:{0} med foresp\u00f8rgsel: {1}
authentication.step.ldap.lookedup=Forespurgte p\u00e5 Test bruger brugernavn:{0}, fandt unikke navn (DN):{1}
authentication.step.ldap.format.user=Brugernavne format specificeret, userNameFormat:{2} Format bruger brugernavn:{0} til at lave unikke navn (DN):{1}
authentication.step.ldap.authentication=Autentificer brugernavn:{0}


# Sync Summary message 
synchronization.summary.status={0} bruger(e) og {1} gruppe(r) behandlet


# Error messages
authentication.ldap.validation.authenticator.notfound=Autentificerer ikke fundet

# Synchronization Diagnostic Steps
synchronization.step.users=Fandt {0} brugere
synchronization.step.groups=Fandt {0} brugere
synchronization.step.users.lastsynced=Brugere som lykkedes sidst at blive synkroniseret {0}
synchronization.step.groups.lastsynced=Grupper som lykkedes sidst at blive synkroniseret {0}

synchronization.err.ldap.search=Fejl under LDAP s\u00f8gning. \u00c5rsag:{0}
synchronization.err.ldap.get.user.id.missing=Bruger mangler brugernavn attribut DN = {0}, attributeName = {1})
synchronization.err.ldap.get.group.id.missing=Gruppe mangler brugernavn attribut DN = {0}, attributeName = {1})

synchronization.err.ldap.search.base.invalid=Invalidt s\u00f8gebase {0} \u00e5rsag: {1}

synchronization.err.ldap.group.member.missing.exception="Kunne ikke hente medlem af gruppe {0} med unikke navn DN: {1}, \u00e5rsag {2});
synchronization.err.ldap.group.member.missing="Kunne ikke hente medlem af gruppe {0} med unikke navn DN: {1});



       



